# Generated by Django 4.2.4 on 2023-09-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_travelinvites'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploads',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='profile_pics', verbose_name='profile pic'),
        ),
    ]
