# Generated by Django 4.2.4 on 2023-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_useruploads_location_alter_useruploads_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinvites',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='travelinvites',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='travelinvites',
            name='location',
        ),
        migrations.AddField(
            model_name='travelinvites',
            name='Destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelinvites',
            name='Location',
            field=models.CharField(max_length=100, null=True, verbose_name='Starting Location'),
        ),
    ]
