# Generated by Django 4.2.4 on 2023-09-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_travelinvites_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploads',
            name='likes',
        ),
    ]
