# Generated by Django 4.2.5 on 2023-09-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_travelinvites_date_useruploads_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinvites',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
