# Generated by Django 4.2.5 on 2023-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_travelinvites_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepictures',
            old_name='pic',
            new_name='Pic',
        ),
        migrations.AddField(
            model_name='profilepictures',
            name='Homeloc',
            field=models.CharField(max_length=100, null=True, verbose_name='Home Location'),
        ),
    ]
