# Generated by Django 4.2.5 on 2023-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rename_pic_profilepictures_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepictures',
            name='Homeloc',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Home Location'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='Pic',
            field=models.ImageField(default=None, upload_to='profile_pics', verbose_name='profile pics'),
        ),
    ]
