# Generated by Django 4.2.5 on 2023-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_profilepictures_homeloc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepictures',
            name='Homeloc',
            field=models.CharField(max_length=100, null=True, verbose_name='Home Location'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='Pic',
            field=models.ImageField(upload_to='profile_pics', verbose_name='profile pics'),
        ),
    ]
